title: David Rodrigo Sánchez Navarro # your name (or website title) here

#logo: "/images/IMGCIC.png?raw=true"
logo: "/images/FotoLinked.jpg?raw=true"

logo2: #"/images/LogoUNMSM.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  UNMSM<br>
  +51991571322<br>
  drodrigosanchezn@gmail.com<br>
  <a href="https://www.linkedin.com/in/rodrigosanchezn/" target="_blank">LinkedIn</a><br>
  <a href="https://www.datacamp.com/profile/rodrigosanchezn" target="_blank">Datacamp</a><br>
  <p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
