title: David Rodrigo Sánchez Navarro # your name (or website title) here
logo: "/images/doomer.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  UNMSM<br>
  +51991571322<br>
  drodrigosanchezn@gmail.com<br>
  <a href="https://www.linkedin.com/in/rodrigosanchezn/" target="_blank">LinkedIn</a><br>
  <a href="https://www.hackerrank.com/drodrigosanchezn/" target="_blank">Hackerrank</a><br>
  <a href="https://www.kaggle.com/drodrigosanchez/" target="_blank">Kaggle</a><br>
  <p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
