title: David Rodrigo Sánchez Navarro # your name (or website title) here
logo: "/images/doomer.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br align="center">
  UNMSM<br>
  +51991571322<br>
  drodrigosanchezn@gmail.com<br>
  <a href="https://www.linkedin.com/in/rodrigosanchezn/">LinkedIn</a><br>
  <a href="https://www.hackerrank.com/drodrigosanchezn/">Hackerrank</a><br>
  <br> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
